FROM mongo:3.2
RUN  apt-get update \
     && apt-get install -y unzip \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

ADD  https://dl.dropboxusercontent.com/u/15056258/mongodb/tweets.zip /data

WORKDIR /data
RUN unzip ./tweets.zip
CMD bash -c "mongorestore --host mongo --port 27017 dump && mongorestore --host mongo_auth --port 27017 dump"