= Mongolastic

What data you have in your MongoDB can also be included into your ElasticSearch and vice versa using this tool. You can perform the aforementioned facilities using the mongolastic query language. Writing a mongolastic query, you explicitly can pass a few specific parameters as well.

== How it works

First, build the source after downloading the latest release from the https://github.com/ozlerhakan/mongolastic/releases[releases] page:

    $ mvn clean install

Second, write a query in a mongolastic file. Mongolastic requires you to give a file ending with `.mongolastic` which contains the query structure:

.the query anatomy
[source,xml]
----
transfer|export|copy database-index-name/collection-type-name
from <declarations>
to  <declarations>

<declarations> := mongo [= <serverConfig>]?
                | es    [= <serverConfig>]?

<serverConfig> := { <properties> [, <properties>]* }

<properties> := port: port-number
              | host: "host-machine"
----

Here is an example of a mongolastic query:

[source,mongolastic]
----
transfer twitter/tweets
from
mongo = { host:"localhost", port: 27017 }
to
es = { host:"localhost", port: 9300 }
----

The following is the equivalent of the previous query:

[source,mongolastic]
----
transfer twitter/tweets from mongo to es
----

And the following one as well:

[source,mongolastic]
----
copy twitter/tweets
from
mongo = { host:"localhost" } <1>
to
es = { port: 9300 } <2>
----
<1> Default number of the mongo port is 27017 and default host is localhost.
<2> Default host and port of es are localhost and 9300 respectively.

NOTE: You can either use upper-case or lower-case for the keywords (e.g. FROM, PORT, etc.)

After building the source and writing a query, you can run the tool by either running:

    $ java -jar target/mongolastic.jar query.mongolastic [key:value key:value ... property6] <1>

<1> _Optionally_, you can *override* the specified value of each property by typing a new key:value pair among the available config pairs.

Or

    $ mvn exec:java -Dexec.args="query.mongolastic [property1 property2 ... property6]"

You can pass the following key:value properties to override the initial settings:

[width="100%",options="header"]
|====================
| Property | Description
| _mongoHost_ |  Specifies the name of the host machine where the `mongod` is running.
| _mongoPort_ |  Specifies the port where the `mongod` instance is listening.
| _db_ *or* _database_ *or* _index_ |  Specifies the _database/index name_ to connect to.
| _c_ *or* _collection_ *or* _type_ |  Specifies the _collection/type name_ to export.
| _esHost_ |  Specifies the name of the host machine where the `elastic node` is running.
| _esPort_ | Specifies the *transport* port where the transport module will communicate with the running elastic node. E.g. *9300* for node-to-node communication.
|====================

IMPORTANT: You can pass parameters up to _6 config key:value pairs_ + _a mongolastic query file_ to Mongolastic. If you pass unknown parameters not being a key:value pair, Mongolastic will discard them and consider the properties of a given query file.

== Examples

=== 1. Example

Let's say your query is as follows:

[source, mongolastic]
----
copy twitter/tweets
from
mongo = { host:"localhost", port: 27017 } to es
----

and you did not pass any extra parameter except the query.mongolastic file, you should a type called "tweets" in an index called "twitter" in your running elastic node listening localhost:9300.

=== 2. Example

Consider the following one that 1 additional parameter is passed along with the mongolastic file:

    $ java -jar target/mongolastic.jar query.mongolastic db:kodcucom c:students

This command will simply ignore twitter/tweets collection and look at the collection called students of the database called kodcucom in order to transfer them into a running elastic node.

== License

Mongolastic is released under the MIT License. See LICENSE file for details.
